spring.application.name=mangakousei-backend

spring.datasource.url=jdbc:postgresql://aws-1-ap-southeast-2.pooler.supabase.com:6543/postgres?sslmode=require
spring.datasource.username=postgres.zqvqcpfivagtguzhnxws
spring.datasource.password=${DB_PASSWORD:}

spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

app.jwt.secret=${JWT_SECRET:}
app.jwt.expiration-milliseconds=10000
app.jwt.remember-me-expiration-milliseconds=604800000