spring.application.name=mangakousei-backend

spring.datasource.url=jdbc:postgresql://aws-1-ap-southeast-2.pooler.supabase.com:6543/postgres?sslmode=require&prepareThreshold=0

spring.datasource.username=
spring.datasource.password=

spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

spring.jpa.properties.hibernate.query.plan_cache_max_size=64
spring.jpa.properties.hibernate.query.plan_parameter_metadata_max_size=32
spring.jpa.properties.hibernate.cache.use_query_cache=false
spring.jpa.properties.hibernate.cache.use_second_level_cache=false

logging.level.org.hibernate.SQL=DEBUG
logging.level.org.hibernate.type.descriptor.sql.BasicBinder=TRACE

spring.datasource.hikari.maximum-pool-size=10
spring.datasource.hikari.minimum-idle=2
spring.datasource.hikari.connection-timeout=30000
spring.datasource.hikari.idle-timeout=600000
spring.datasource.hikari.max-lifetime=1800000

spring.datasource.hikari.data-source-properties.stringtype=unspecified
spring.datasource.hikari.data-source-properties.cachePrepStmts=false
spring.datasource.hikari.data-source-properties.prepStmtCacheSize=0
spring.datasource.hikari.data-source-properties.prepStmtCacheSqlLimit=0

app.jwt.secret=
# 15 phut
app.jwt.expiration-milliseconds=900000

# 7 ngay
app.jwt.remember-me-expiration-milliseconds=604800000
# 1 ngay
app.jwt.refresh-expirationMs-milliseconds=86400000

cloudinary.cloud-name=
cloudinary.upload-preset=
spring.servlet.multipart.max-file-size=5MB
spring.servlet.multipart.max-request-size=5MB
